// Auto-generated by scripts/update-reviews.mjs
export const googleReviews = [
  {
    "name": "Morz",
    "text": "ליאב ואושרי המקצוענים\nהזמנו אותם לחתונה בטבע שעשינו לפני חצי שנה.\nאף אחד מהאורחים לא ציפה לשירות כזה … עוד",
    "initial": "M",
    "image": "/images/avatars/avatar_morz_0.jpg",
    "link": "https://www.google.com/maps/contrib/117111785835596387629/reviews?hl=iw",
    "color": "bg-blue-500"
  },
  {
    "name": "מושיקו חיים לוי",
    "text": "שכרתי שירותים ניידים לאירוע שעשיתי בשטח והייתי מאוד מרוצה מהשירות!\nהציוד הגיע בזמן, הכל היה נקי, מסודר ומתוחזק ברמה גבוהה. השירותים היו מרווחים ונעימים לשימוש, והאורחים באירוע אפילו ציינו לטובה את רמת הניקיון – וזה ממש לא מובן … עוד",
    "initial": "מ",
    "image": "/images/avatars/avatar_________________1.jpg",
    "link": "https://www.google.com/maps/contrib/111821951457040260538/reviews?hl=iw",
    "color": "bg-emerald-500"
  },
  {
    "name": "Or Hadar",
    "text": "רוצה להמליץ מכל הלב! מעבר לזה שהקרונות עצמם מפוארים, מריחים מעולה ומאובזרים בכל מה שצריך, השירות של הצוות היה פשוט מעל ומעבר. הם דאגו לכל פרט קטן עם חיוך, ושמרו על המקום מבריק לאורך כל הערב. האורחים הרגישו שהשקיעו בהם עד הסוף. מקצוענים אמיתיים שנותנים שקט נפשי מלא.",
    "initial": "O",
    "image": "/images/avatars/avatar_or_hadar_2.jpg",
    "link": "https://www.google.com/maps/contrib/114395330595132092387/reviews?hl=iw",
    "color": "bg-purple-500"
  },
  {
    "name": "Avi Kazav",
    "text": "עשינו חתונה והיינו צריכים שירותים מפוארים לאורחים, וכך הגענו לליאב שנתן שירות מדהים.\nשירותים מפוארים עם איש תחזוקה בשטח לאורך כל האירוע ברמה של מלון 5 כוכבים!!!\nתודה רבה על הכולל",
    "initial": "A",
    "image": "/images/avatars/avatar_avi_kazav_3.jpg",
    "link": "https://www.google.com/maps/contrib/107588140169912078050/reviews?hl=iw",
    "color": "bg-rose-500"
  },
  {
    "name": "Gal musix",
    "text": "הזמנו שירותים ניידים לאירוע וקיבלנו שירות מצוין. השירותים הגיעו בזמן, היו נקיים ומתוחזקים לאורך כל האירוע. הצוות היה מקצועי ואדיב, ודאג לכל מה שהיה צריך במהירות. פתרון נוח ואיכותי לאירועים בשטח או בטבע. ממליץ מאוד!",
    "initial": "G",
    "image": "/images/avatars/avatar_gal_musix_4.jpg",
    "link": "https://www.google.com/maps/contrib/109114610310788767857/reviews?hl=iw",
    "color": "bg-amber-500"
  },
  {
    "name": "yoheved hyayev",
    "text": "שירות ממש מעולה ניקיון מטורף וריח מושלם שאין לתאר!!\nשמחה מאוד שבחרתי בכם אין אחד שלא החמיא לכם\nתודה רבה על השירות 🥇🤗🥰 …",
    "initial": "y",
    "image": "/images/avatars/avatar_yoheved_hyayev_5.jpg",
    "link": "https://www.google.com/maps/contrib/108230227738858252923/reviews?hl=iw",
    "color": "bg-cyan-500"
  },
  {
    "name": "Edan Gareya",
    "text": "ממליץ בחום על א.ל שירותים ניידים רמת ניקיון יוצאת דופן ושירות מקצועי ואדיב. השירותים המפוארים שדרגו את האירוע בשטח בכמה רמות. פשוט חוויה של מלון בלב הטבע. מומלץ מאוד!\"",
    "initial": "E",
    "image": "/images/avatars/avatar_edan_gareya_6.jpg",
    "link": "https://www.google.com/maps/contrib/108766302868936184741/reviews?hl=iw",
    "color": "bg-indigo-500"
  },
  {
    "name": "אורה לי גולדבך",
    "text": "הופתעתי ממש!  מרגיש שירותים רגילים! נקי, מואר יש שטיפת ידיים ואמצעים לרענון. לא השירותים הכימיים שהיו לנו בתנועה.... משהו משהו!  ממליצה מאוד!",
    "initial": "א",
    "image": "/images/avatars/avatar________________7.jpg",
    "link": "https://www.google.com/maps/contrib/109721541685324624737/reviews?hl=iw",
    "color": "bg-pink-500"
  },
  {
    "name": "Naor Levi",
    "text": "אם אתם מחפשים שירותים ניידים שבאמת נראים טוב ונקיים ששווה להשכיר אז ממליץ על א.ל שירותים ניידים הם הכי טובים והכי זולים.",
    "initial": "N",
    "image": "/images/avatars/avatar_naor_levi_8.jpg",
    "link": "https://www.google.com/maps/contrib/113358221810149586077/reviews?hl=iw",
    "color": "bg-teal-500"
  },
  {
    "name": "Orel Hdad",
    "text": "אחלה שירות אדיבים נראה נקי ומסודר ממליץ בחום",
    "initial": "O",
    "image": "/images/avatars/avatar_orel_hdad_9.jpg",
    "link": "https://www.google.com/maps/contrib/114247325200361467931/reviews?hl=iw",
    "color": "bg-blue-500"
  },
  {
    "name": "Valera Sonis",
    "text": "וואו, פשוט חוויה אחרת. נקי ברמה בוהקת, מריח מעולה ומעוצב בטוב טעם. זה מרגיש כמו להיכנס לבית מלון באמצע השטח. שירות מקצועי ואדיב מאוד, תודה רבה!",
    "initial": "V",
    "image": "/images/avatars/avatar_valera_sonis_10.jpg",
    "link": "https://www.google.com/maps/contrib/114149896483637837012/reviews?hl=iw",
    "color": "bg-emerald-500"
  },
  {
    "name": "Gregory Stoyanov",
    "text": "ממליץ לכל מי שצריך להשכיר נגרר שירותים לאירוע שלו רציתי להגיד תודה רבה לליאב ולצוות של המקצוענים שתמיד היה זמין ותפעל את השירותים כמו שצריך שאפו!!!!!",
    "initial": "G",
    "image": "/images/avatars/avatar_gregory_stoyanov_11.jpg",
    "link": "https://www.google.com/maps/contrib/115571783275684119717/reviews?hl=iw",
    "color": "bg-purple-500"
  },
  {
    "name": "נוי יעיש",
    "text": "השכרנו שירותים ניידים לאירוע והחוויה הייתה מצוינת. השירותים היו ברמה גבוהה, נקיים ומתוחזקים היטב, והשירות שקיבלנו היה אדיב, מקצועי ומהיר. מומלץ מאוד לכל אירוע",
    "initial": "נ",
    "image": "/images/avatars/avatar__________12.jpg",
    "link": "https://www.google.com/maps/contrib/115255766507082891166/reviews?hl=iw",
    "color": "bg-rose-500"
  },
  {
    "name": "rivka aronov",
    "text": "קיבלתי שירות נדיר תודה רבה לליאב ואושרי אין ספק שאזמין שוב",
    "initial": "r",
    "image": "/images/avatars/avatar_rivka_aronov_13.jpg",
    "link": "https://www.google.com/maps/contrib/106013331323155725216/reviews?hl=iw",
    "color": "bg-amber-500"
  },
  {
    "name": "Kiril Tril",
    "text": "הייתי בחתונה והשירותים פשוט מושלמים\nהכול היה מסודר ונקי",
    "initial": "K",
    "image": "/images/avatars/avatar_kiril_tril_14.jpg",
    "link": "https://www.google.com/maps/contrib/117619937984864630860/reviews?hl=iw",
    "color": "bg-cyan-500"
  },
  {
    "name": "Aviel David",
    "text": "ממליץ בחום הגיעו בזמן הביאו לנו שקט ונחת באירוע",
    "initial": "A",
    "image": "/images/avatars/avatar_aviel_david_15.jpg",
    "link": "https://www.google.com/maps/contrib/101605100820853979758/reviews?hl=iw",
    "color": "bg-indigo-500"
  },
  {
    "name": "נתנאלה שטרנברג",
    "text": "היה לנו אירוע בשטח פתוח הזמנו שירותים ניידים והכול עבד חלק ההגעה הייתה מדויקת ההתקנה מהירה והשירותים היו מתוחזקים ונקיים לאורך כל האירוע",
    "initial": "נ",
    "image": "/images/avatars/avatar________________16.jpg",
    "link": "https://www.google.com/maps/contrib/115120852583759553551/reviews?hl=iw",
    "color": "bg-pink-500"
  },
  {
    "name": "אלי בן לולו",
    "text": "שירות לקוחות מדהים\nמגיע נקי מסודר בעל העסק אדם ישר והגון",
    "initial": "א",
    "image": "/images/avatars/avatar_____________17.jpg",
    "link": "https://www.google.com/maps/contrib/114285842506897223299/reviews?hl=iw",
    "color": "bg-teal-500"
  },
  {
    "name": "נאור שוקני",
    "text": "תודה על הכול שיחקתם אותה שירות איכות ומחיר 10/10",
    "initial": "נ",
    "image": "/images/avatars/avatar____________18.jpg",
    "link": "https://www.google.com/maps/contrib/100020124553754523565/reviews?hl=iw",
    "color": "bg-blue-500"
  },
  {
    "name": "yarin",
    "text": "הזמנתי אותו לחתונה ביער, פשוט היה תענוג כל האורחים החמיאו ואמרו שזאת החתונה ביער הראשונה שלהם שהיה שירותים נורמלים ומענגים.ליד השירותים היה איש צמוד שרק ניקה הכל פשוט היה מצוחצח ונקי\nממליץ מאוד.",
    "initial": "y",
    "image": "/images/avatars/avatar_yarin_19.jpg",
    "link": "https://www.google.com/maps/contrib/105588727629578961585/reviews?hl=iw",
    "color": "bg-emerald-500"
  },
  {
    "name": "יוסף ברזילי",
    "text": "אחלה שירות אנשים טובים ממליץ לכם",
    "initial": "י",
    "image": "/images/avatars/avatar_____________20.jpg",
    "link": "https://www.google.com/maps/contrib/114565532071720887265/reviews?hl=iw",
    "color": "bg-purple-500"
  },
  {
    "name": "אושרי מגרו",
    "text": "שירות נהדר בחורים זהב",
    "initial": "א",
    "image": "/images/avatars/avatar____________21.jpg",
    "link": "https://www.google.com/maps/contrib/117121088395213432589/reviews?hl=iw",
    "color": "bg-rose-500"
  },
  {
    "name": "דודו עזר",
    "text": "ממליץ עליכם בחום צוות של אלופיםם",
    "initial": "ד",
    "image": "/images/avatars/avatar__________22.jpg",
    "link": "https://www.google.com/maps/contrib/107980149704454530701/reviews?hl=iw",
    "color": "bg-amber-500"
  },
  {
    "name": "מירית מיכאלי",
    "text": "שירות מעולה!! ריח מושלם!!",
    "initial": "מ",
    "image": "/images/avatars/avatar______________23.jpg",
    "link": "https://www.google.com/maps/contrib/118166374354593200351/reviews?hl=iw",
    "color": "bg-cyan-500"
  },
  {
    "name": "טוביה דבח",
    "text": "רוצה לפרגן לכם צוות של אלופים שמגיע מגיעע!!!!",
    "initial": "ט",
    "image": "/images/avatars/avatar___________24.jpg",
    "link": "https://www.google.com/maps/contrib/116711096302430417370/reviews?hl=iw",
    "color": "bg-indigo-500"
  },
  {
    "name": "רועי סבאן",
    "text": "אלופים שירותים מעולים כמו בבית",
    "initial": "ר",
    "image": "/images/avatars/avatar___________25.jpg",
    "link": "https://www.google.com/maps/contrib/113356424591230108193/reviews?hl=iw",
    "color": "bg-pink-500"
  },
  {
    "name": "david ben moshe",
    "text": "תודה על הכול אלופייםםם !!",
    "initial": "d",
    "image": "/images/avatars/avatar_david_ben_moshe_26.jpg",
    "link": "https://www.google.com/maps/contrib/102132514056929887301/reviews?hl=iw",
    "color": "bg-teal-500"
  },
  {
    "name": "תומר דיירי",
    "text": "פשוט וואוו אין מילים",
    "initial": "ת",
    "image": "/images/avatars/avatar____________27.jpg",
    "link": "https://www.google.com/maps/contrib/106458440970829629785/reviews?hl=iw",
    "color": "bg-blue-500"
  },
  {
    "name": "aviel esperansa",
    "text": "חוויה רצינית",
    "initial": "a",
    "image": "/images/avatars/avatar_aviel_esperansa_28.jpg",
    "link": "https://www.google.com/maps/contrib/110820773772325237254/reviews?hl=iw",
    "color": "bg-emerald-500"
  },
  {
    "name": "simi bitton",
    "text": "נקי יפה מסודר ונעים",
    "initial": "s",
    "image": "/images/avatars/avatar_simi_bitton_29.jpg",
    "link": "https://www.google.com/maps/contrib/108000632457345499757/reviews?hl=iw",
    "color": "bg-purple-500"
  },
  {
    "name": "יניב בן מיור",
    "text": "כמו בבית נקי מסודר ומפנק",
    "initial": "י",
    "image": "/images/avatars/avatar______________30.jpg",
    "link": "https://www.google.com/maps/contrib/105580138719954407077/reviews?hl=iw",
    "color": "bg-rose-500"
  },
  {
    "name": "הפריקסה של חיימיקו",
    "text": "אירוע שמכבד את עצמו ולא שם שירותים כאלה , לא מכבד את האורחים שלו",
    "initial": "ה",
    "image": "/images/avatars/avatar____________________31.jpg",
    "link": "https://www.google.com/maps/contrib/107268401591760593451/reviews?hl=iw",
    "color": "bg-amber-500"
  },
  {
    "name": "Elior",
    "text": "שירותים נוחים מאוד ושירות מדהים!",
    "initial": "E",
    "image": "/images/avatars/avatar_elior_32.jpg",
    "link": "https://www.google.com/maps/contrib/112640547277126563871/reviews?hl=iw",
    "color": "bg-cyan-500"
  },
  {
    "name": "see forfun",
    "text": "אלוף שתומך בהלומי קרב ממליץ\nבן אדם נדיר",
    "initial": "s",
    "image": "/images/avatars/avatar_see_forfun_33.jpg",
    "link": "https://www.google.com/maps/contrib/118054986218147317100/reviews?hl=iw",
    "color": "bg-indigo-500"
  },
  {
    "name": "אריאל בוארון",
    "text": "מקצוענים הכל נקי שירות מעולה ❤️",
    "initial": "א",
    "image": "/images/avatars/avatar______________34.jpg",
    "link": "https://www.google.com/maps/contrib/117631786973616913846/reviews?hl=iw",
    "color": "bg-pink-500"
  },
  {
    "name": "hodaya asayag",
    "text": "מקצוענייייםםם!!!!",
    "initial": "h",
    "image": "/images/avatars/avatar_hodaya_asayag_35.jpg",
    "link": "https://www.google.com/maps/contrib/105497854514872106401/reviews?hl=iw",
    "color": "bg-teal-500"
  },
  {
    "name": "Be Aware",
    "text": "שירות צוות של אלופים",
    "initial": "B",
    "image": "/images/avatars/avatar_be_aware_36.jpg",
    "link": "https://www.google.com/maps/contrib/104866696885223085222/reviews?hl=iw",
    "color": "bg-blue-500"
  },
  {
    "name": "חנה מרדכי",
    "text": "שירותים מהממיםם העיצוב נדיר\nריח טוב ותמיד נקי",
    "initial": "ח",
    "image": "/images/avatars/avatar___________37.jpg",
    "link": "https://www.google.com/maps/contrib/107019630939626987555/reviews?hl=iw",
    "color": "bg-emerald-500"
  },
  {
    "name": "Ariela Ozeri",
    "text": "פעם ראשונה שאני באה למסיבה בשטח וזה פשוט מעל המצופה,\nנקי מושקע, ריח טוב ויש מסטיקים, דאודורנט , והפתעות ליד הכיור!!!\nבאמת שאפו!!!\nמומלץ בטירוף",
    "initial": "A",
    "image": "/images/avatars/avatar_ariela_ozeri_38.jpg",
    "link": "https://www.google.com/maps/contrib/106838330904866094793/reviews?hl=iw",
    "color": "bg-purple-500"
  },
  {
    "name": "Liran Matityahuyahu",
    "text": "הזמנתי את א.ל שירותים ניידים, ממליץ בחום יש להם שירות מעולה ונתנו לי שקט באירוע🌟 …",
    "initial": "L",
    "image": "/images/avatars/avatar_liran_matityahuyahu_39.jpg",
    "link": "https://www.google.com/maps/contrib/106781887656774762751/reviews?hl=iw",
    "color": "bg-rose-500"
  },
  {
    "name": "אלירן שיטרית",
    "text": "צוות של אלופים רמה גבוה מאוד מממליץ בחום",
    "initial": "א",
    "image": "/images/avatars/avatar______________40.jpg",
    "link": "https://www.google.com/maps/contrib/102283681844095232931/reviews?hl=iw",
    "color": "bg-amber-500"
  },
  {
    "name": "משה אליהו",
    "text": "עשינו אירוע בשטח והזמנו שירותים ניידים מפוארים דרך ליאב, והחוויה הייתה פשוט מצוינת.\nהשירות היה ברמה גבוהה מאוד—מקצועי, אדיב וזמין לכל שאלה או בקשה. … עוד",
    "initial": "מ",
    "image": "/images/avatars/avatar___________41.jpg",
    "link": "https://www.google.com/maps/contrib/104369630685862930631/reviews?hl=iw",
    "color": "bg-cyan-500"
  },
  {
    "name": "ניר דקל",
    "text": "שירות ברמה בינלאומית, שירות מכל הלב!",
    "initial": "נ",
    "image": "/images/avatars/avatar_________42.jpg",
    "link": "https://www.google.com/maps/contrib/115932273308010107398/reviews?hl=iw",
    "color": "bg-indigo-500"
  },
  {
    "name": "מירי שפיר",
    "text": "",
    "initial": "מ",
    "image": "/images/avatars/avatar___________43.jpg",
    "link": "https://www.google.com/maps/contrib/113271466504494597687/reviews?hl=iw",
    "color": "bg-pink-500"
  },
  {
    "name": "רינת עמר",
    "text": "",
    "initial": "ר",
    "image": "/images/avatars/avatar__________44.jpg",
    "link": "https://www.google.com/maps/contrib/114022727271262438320/reviews?hl=iw",
    "color": "bg-teal-500"
  },
  {
    "name": "מתן מולר",
    "text": "",
    "initial": "מ",
    "image": "/images/avatars/avatar__________45.jpg",
    "link": "https://www.google.com/maps/contrib/104228115700998289504/reviews?hl=iw",
    "color": "bg-blue-500"
  }
];
